name: Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
      - name: Install Android SDK
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
      - run: flutter pub cache clean
      - run: flutter pub get
      - run: flutter build apk