name: Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          flutter-version: "3.27.4"
      - name: Set Gradle properties
        run: |
          echo "org.gradle.java.home=$JAVA_HOME" >> android/gradle.properties
          echo "org.gradle.jvmargs=-Xmx4096m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> android/gradle.properties
          echo "android.enableJetifier.force=false" >> android/gradle.properties
      - name: Clean Flutter
        run: flutter clean
      - run: flutter pub cache clean
      - run: flutter pub get
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons